play.application.loader = "modules.AppLoader"

play.http.router = "router.Routes"

// CORS (dev). In production, serve frontend from Play and you can remove this.
play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.enabled += "play.filters.csrf.CSRFFilter"
play.filters.cors.allowedOrigins = [
  "http://localhost:5173"
]
play.filters.cors.allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
play.filters.cors.allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "Authorization"]
play.filters.cors.preflightMaxAge = 1h
play.filters.cors.allowCredentials = true
play.filters.csrf.cookie.name="csrfToken"
play.filters.csrf.header.name="Csrf-Token"

// Slick database config (H2 embedded: no install required).
db.default.profile = "slick.jdbc.H2Profile$"
db.default.db {
  driver = "org.h2.Driver"
  url = "jdbc:h2:file:./data/notesdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1"
  user = "sa"
  password = ""
  connectionPool = "HikariCP"
  numThreads = 10
}

// Use a dedicated secret in real deployments
play.http.secret.key="CHANGE_ME_IN_PROD_32+_CHARS________________________________"

security.argon2.iterations = 3
security.argon2.memoryKb = 65536
security.argon2.parallelism = 1
security.argon2.saltLength = 16
security.argon2.hashLength = 32
security.login.maxDailyAttempts = 3
